VALIDATE_DATA_PATH = "../CFM-Dataset/40800-Action7/one_hot_validate_orig"
BATCH_SIZE = 32
NUM_OF_VALIDATE_SAMPLES = 256
STEPS_OF_VALIDATE = NUM_OF_VALIDATE_SAMPLES // BATCH_SIZE
CLASSES_NUM = 6

ACTION_NAME = [
    "MOVE_FORWARD",
    "MOVE_BACKWARD",
    "MOVE_LEFT",
    "MOVE_RIGHT",
    "TURN_LEFT",
    "TURN_RIGHT",
    "NO_ACTION"
]